BookyWeb/Areas/Admin/Controllers/CompanyController.cs
using Booky.DataAccess.Repositries;
using Booky.DataAccess.Repositries.IRepository;
using Booky.Models;
using Booky.Models.ViewModels;
using Booky.Services;
using Booky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;

namespace BookyWeb.Areas.Admin.Controllers
{
    [Area(areaName: "Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CompanyController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IFileService fileService;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var companies = unitOfWork.Company.GetAll();

            return View("Index", companies);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            Company company;

            // creating (inserting) a new product
            if (id == null || id == 0)
            {
                company = new Company();
            } else
            {
                company = unitOfWork.Company.Get(c => c.Id == id);
            }

            return View("Upsert", company);
        }

        [HttpPost]
        public IActionResult Upsert(Company company)
        {

            if (ModelState.IsValid)
            {

                if (company.Id == 0)
                {
                    unitOfWork.Company.Add(company);
                    // Notification
                    TempData["success"] = "Company created successfully.";
                }
                else 
                { 
                    unitOfWork.Company.Update(company);
                    // Notification
                    TempData["success"] = "Company updated successfully.";
                }

                unitOfWork.Save();

                return RedirectToAction("Index");
            } else
            {
                
                return View("Upsert", company);
            }
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> companies = unitOfWork.Company.GetAll().ToList();
            return Json(new {data = companies});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companyToBeDeleted = unitOfWork.Company.Get(c => c.Id == id);
            if (companyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            
            unitOfWork.Company.Delete(companyToBeDeleted);
            unitOfWork.Save();

            return Json(new { success = true, message = "Company deleted successfully." });
        }
    }
}

BookyWeb/Areas/Admin/Controllers/OrderController.cs
using Booky.DataAccess.Repositries;
using Booky.DataAccess.Repositries.IRepository;
using Booky.Models;
using Booky.Models.ViewModels;
using Booky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;

namespace BookyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;            
        }

        public IActionResult Index()
        {

            return View("Index");
        }

        [HttpGet]
        public IActionResult Details(int orderId)
        {
            OrderVM orderVM = new OrderVM
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetail.GetAll(o => o.OrderHeader.Id == orderId, includeProperties: "Product")
            };
            return View("Details", orderVM);
        }

        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult UpdateOrderDetail(OrderVM orderVM)
        {
            // we need to update the database with the new values
            OrderHeader orderHeaderFromDb = _unitOfWork.OrderHeader
                .Get(o => o.Id == orderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = orderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = orderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = orderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = orderVM.OrderHeader.City;
            orderHeaderFromDb.State = orderVM.OrderHeader.State;
            orderHeaderFromDb.PostalCode = orderVM.OrderHeader.PostalCode;

            if (!string.IsNullOrEmpty(orderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = orderVM.OrderHeader.TrackingNumber;
            }

            if (!string.IsNullOrEmpty(orderVM.OrderHeader.Carrier))
            {
                orderHeaderFromDb.Carrier = orderVM.OrderHeader.Carrier;
            }

            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();

            var refreshedOrderVM = new OrderVM
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(
                                o => o.Id == orderVM.OrderHeader.Id,
                                includeProperties: "ApplicationUser"),

                OrderDetails = _unitOfWork.OrderDetail.GetAll(
                                o => o.OrderHeaderId == orderVM.OrderHeader.Id,
                            includeProperties: "Product")
            };

            return View("Details", refreshedOrderVM);

        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing(OrderVM orderVM)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["success"] = "Order Details Updated Successfuly.";

            return RedirectToAction("Details", new {orderId = orderVM.OrderHeader.Id});
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder(OrderVM orderVM)
        {
            OrderHeader orderHeaderDB = _unitOfWork.OrderHeader.Get(o => o.Id == orderVM.OrderHeader.Id);
            orderHeaderDB.TrackingNumber = orderVM.OrderHeader.TrackingNumber;
            orderHeaderDB.Carrier = orderVM.OrderHeader.Carrier;
            orderHeaderDB.OrderStatus = SD.StatusShipped;
            orderHeaderDB.ShippingDate = DateTime.Now;
            if(orderHeaderDB.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeaderDB.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.OrderHeader.Update(orderHeaderDB);
            _unitOfWork.Save();

            TempData["success"] = "Order Shipped Successfuly.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult CancelOrder(OrderVM orderVM)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderVM.OrderHeader.Id);

            if(orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions()
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId
                };
                var service = new RefundService();
                Refund refund = service.Create(options);

                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            } else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }

            _unitOfWork.Save();
            TempData["success"] = "Order Canceled Successfuly.";
            return RedirectToAction("Details", new { orderId = orderHeader.Id });
        }

        public IActionResult PaymentConfirmation(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderId);
            if (orderHeader == null) return NotFound();

            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeader.UpdateStripePaymentId(orderId, session.Id, session.PaymentIntentId);
                    _unitOfWork.OrderHeader.UpdateStatus(orderId, orderHeader.OrderStatus, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                }
    
            }


            return View("PaymentConfirmation", orderId);
        }

        [ActionName("Details")]
        [HttpPost]
        public IActionResult Details_Pay_Now(OrderVM orderVM)
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderVM.OrderHeader.Id);
            var orderDetails = _unitOfWork.OrderDetail.GetAll(o => o.OrderHeaderId == orderVM.OrderHeader.Id, includeProperties: "Product");

            //StripeConfiguration.ApiKey = _config["Stripe:SecretKey"];
            var domain = "http://localhost:5214/";
            var options = new Stripe.Checkout.SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderId={orderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?orderId={orderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };
            foreach (var item in orderDetails)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.price * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new Stripe.Checkout.SessionService();
            Session session = service.Create(options);

            _unitOfWork.OrderHeader.UpdateStripePaymentId(orderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        [HttpGet]
        public IActionResult GetAll(string status)
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            IEnumerable<OrderHeader> orderHeaders;

            //get all the orders if the user is an admin or employee
            if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            {
                orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser");
            }
            else
            {
                //get the orders of the signed in user
                orderHeaders = _unitOfWork.OrderHeader.GetAll(o=>o.ApplicationUserId == userId,
                    includeProperties: "ApplicationUser");
            }

            
            switch (status)
            {
                case "pending":
                    orderHeaders = orderHeaders.Where(o => o.PaymentStatus == SD.PaymentStatusDelayedPayment);
                        break;
                case "inprocess":
                    orderHeaders = orderHeaders.Where(o => o.OrderStatus == SD.StatusInProcess);
                    break;
                case "completed":
                    orderHeaders = orderHeaders.Where(o => o.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    orderHeaders = orderHeaders.Where(o => o.OrderStatus == SD.StatusApproved);
                    break;
                default:
                    break;
            }
            return Json(new { data = orderHeaders });
        }
    }
}

BookyWeb/Controllers/CateogryController.cs
using Booky.Models;
using Microsoft.AspNetCore.Mvc;
using Booky.DataAccess.Repositries.IRepository;

namespace BookyWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var categoryList = unitOfWork.Category.GetAll().OrderBy(c => c.DisplayOrder).ToList();

            return View("Index", categoryList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Category newCategory)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Category.Add(newCategory);
                unitOfWork.Category.Save();
                TempData["success"] = "Category created successfully.";
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if(id == 0) return NotFound();

            var model = unitOfWork.Category.Get(c => c.Id == id);
            if(model == null) return NotFound();

            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Category.Update(category);
                unitOfWork.Category.Save();
                TempData["success"] = "Category updated successfully.";
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if(id == 0) return NotFound();
            
            var model = unitOfWork.Category.Get(c=>c.Id == id);
            if(model == null) return NotFound();
            
            return View("Delete", model);
        }

        [HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            var category = unitOfWork.Category.Get(c=>c.Id==id);
            unitOfWork.Category.Delete(category);
            unitOfWork.Category.Save();
            TempData["success"] = "Category deleted successfully.";
            return RedirectToAction("Index");
        }
    }
}

BookyWeb/ViewComponents/ShoppingCartViewComponent.cs
using Booky.DataAccess.Repositries;
using Booky.DataAccess.Repositries.IRepository;
using Booky.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookyWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            string? userId = HttpContext.User.Claims?.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            if (userId != null)
            {
                //logged in case
                int? sessionCartCount = HttpContext.Session.GetInt32(SD.SessionCart);
                if (sessionCartCount == null)
                {
                    sessionCartCount = _unitOfWork.ShoppingCart.GetAll(sc => sc.ApplicationUserId == userId).Count();
                    HttpContext.Session.SetInt32(SD.SessionCart, (int)sessionCartCount);
                    
                }
                return View(sessionCartCount);
            } else
            {
                //logged out case
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BookyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="Admin" asp-controller="Category" asp-action="Index" class="dropdown-item">Category</a></li>
                                    <li><a asp-area="Admin" asp-controller="Product" asp-action="Index" class="dropdown-item">Product</a></li>
                                    <li><a asp-area="Admin" asp-controller="Company" asp-action="Index" class="dropdown-item">Company</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a asp-area="Identity" asp-page="/Account/Register" class="dropdown-item">Create User</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" mb-3 pb-3" style="min-height:100vh">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary ">
       
        <div class="container text-center">
            &copy; 2025 - BookyWeb - Made with <i class="bi bi-heart-fill"></i> by Youssef El-Nemaky
        </div>
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}